# Generated by Django 5.2.4 on 2025-08-15 13:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0002_destinatario_documento_archivo_documento_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmittal',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transmittal',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='transmittals.documento'),
        ),
    ]
