# Generated by Django 5.2.4 on 2025-08-18 01:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0003_transmittal_actualizado_en_transmittal_creado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='destinatario',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='transmittal',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transmittals_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transmittal',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transmittal',
            name='observacion_general',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transmittal',
            name='proposito_envio',
            field=models.CharField(choices=[('APROBACION', 'Solicita Aprobación'), ('REVISION', 'Requiere Revisión'), ('RESPUESTA', 'Requiere Respuesta'), ('INFO', 'Informativo')], default='INFO', max_length=15),
        ),
        migrations.AlterField(
            model_name='transmittal',
            name='asunto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transmittal',
            name='destinatarios',
            field=models.ManyToManyField(blank=True, related_name='transmittals', to='transmittals.destinatario'),
        ),
        migrations.AlterField(
            model_name='transmittal',
            name='documentos',
            field=models.ManyToManyField(blank=True, related_name='transmittals', to='transmittals.documento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transmittals.especialidad'),
        ),
    ]
