name: CI - SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "main" ]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # si NO tienes sonar-project.properties, pasa los args aquí:
          args: >
            -Dsonar.organization=TU_ORG
            -Dsonar.projectKey=TU_ORG_WEBTML_LIMPIO
            -Dsonar.sources=.
            -Dsonar.exclusions=**/migrations/**,**/static/**,**/media/**,**/node_modules/**,**/.venv/**,**/venv/**,**/__pycache__/**

    
